### ISSUE TITLE
any interest in an environment.yml file?

### ISSUE THREAD

**Issue by jsta** [KMarkert/hydrate#2]
I see that a complete package list is already in the Dockerfile. It just doesn't match the README.

**Comment by KMarkert** [comment]
Hi @jsta 👋 

Yes, documentation is lacking the dev on this package unfortunately fell off due to time constraints but some core functionality will work. I think it would be great to include an environment.yml file to help users with installation and setup. The Dockerfile should have all the dependencies listed but it is two years old so some of the specified dependency version may need to checked.

Are you interested in submitting a PR with the environment.yml info? Contributions are welcome and all your work will be attributed!
